#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2011-2013 Carlos Jenkins <carlos@jenkins.co.cr>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.


"""
Nested project runner.
"""

import os
import sys
from os.path import normpath, dirname, abspath, realpath, join, isfile


root = normpath(dirname(abspath(realpath(__file__))))
bindirs = [join(root, 'src/bin/'), join(root, 'test/')]


def main():

    if len(sys.argv) != 2:
        print('Usage: ./run [program|test]')
        sys.exit(1)

    os.chdir(root)

    bin = sys.argv[1]

    for bdir in bindirs:
        path = join(bdir, bin)
        if isfile(path) and os.access(path, os.X_OK):
            cmd = 'PYTHONPATH=$PYTHONPATH:{} {}'.format(
                    join(root, 'src/lib/'), path
                )
            print('Running:\n\t{}'.format(cmd))
            ret = os.system(cmd)
            sys.exit(ret)

    print('ERROR: test or program "{}"" not found.'.format(bin))
    sys.exit(1)


if __name__ == '__main__':
    main()

